export let state = {
  cursos: ['General'],
  tareas: [],
  eventos: [],
  apuntes: [],
  proyectos: [],
  proyectoSeleccionadoId: null,
  config: { theme: 'light', accent_color: '#0078d7' },
  paginaActual: 'dashboard',
  tareaSeleccionadald: null,
  ordenamiento: { col: 'fecha', reverse: false },
  filtroCurso: 'todos',
  filtroCursoApuntes: 'todos',
  apuntesEnModoSeleccion: false,
  apuntesSeleccionadosIds: [],
};
