export let state = {
  cursos: ['General'],
  tareas: [],
  eventos: [],
  apuntes: [],
  proyectos: [],
  proyectoSeleccionadoId: null,
  config: {
    theme: 'light',
    accent_color: '#0078d7',
    userName: null,
    widgetsVisibles: {
      racha: true,
      enfoque: true,
      proximamente: true,
      eventos: true,
      progresoSemanal: true,
      accesos: true,
      cargaSemanal: true,
      pomodoro: true,
      apuntesRecientes: true,
      progresoProyectos: true,
      tareasVencidas: true,
    },
  },
  paginaActual: 'dashboard',
  tareaSeleccionadald: null,
  ordenamiento: { col: 'fecha', reverse: false },
  filtroCurso: 'todos',
  filtroCursoApuntes: 'todos',
  apuntesEnModoSeleccion: false,
  apuntesSeleccionadosIds: [],
};
